version: 2
jobs:
  build:
    deploy:
    docker: 
      - image: circleci/node:8.11.3
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true 

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}


      - run:
          name: Deploy Master to Heroku
          command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
              git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
              fi

    
  